version: '3'

services:
  librerest:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3030:3000"
    volumes:
      - .:/app
    environment:
      - URL=http://localhost:3000